Solution
mate-academy/js_get_data_DOM pull request #385
Opened 2022-01-21 20:17 UTC by dima-cherednyk

- [DEMO LINK](https://dima-cherednyk.github.io/js_get_data_DOM/)

2022-01-24 10:20 UTC, aliceblunt8 requested changes

2022-01-24 10:20 UTC, aliceblunt8 commented on src/scripts/main.js
> +const numbers = texts.map(x => +x.replace(/,/g, ''));
combine these 2 map methods into one

2022-01-24 10:20 UTC, aliceblunt8 commented on src/scripts/main.js
> +average.textContent = averageToString;
```suggestion
total.textContent = totalAmount.toLocaleString('en-US');
average.textContent = (totalAmount / numbers.length).toLocaleString('en-US');
```

2022-01-24 10:20 UTC, aliceblunt8 commented on src/scripts/main.js
> +// console.log(total, average);
remove console.log

2022-01-24 10:20 UTC, aliceblunt8 commented on src/scripts/main.js
> +const average = document.querySelector('.average-population');
move all querySelector and querySelectorAll to the beginning of the file

2022-01-25 13:12 UTC, aliceblunt8 requested changes
fix comments from previous review or if you did this then push to Github, I don't see a new commit after review

2022-01-25 19:29 UTC, dima-cherednyk commented
Problems with push.

2022-01-25 19:50 UTC, dima-cherednyk commented
> 
fixed in dev01

2022-01-26 14:13 UTC, closed without merging