Solution
mate-academy/js_get_data_DOM pull request #510
Opened 2022-07-19 12:40 UTC by Kras4iy

- [DEMO LINK](https://<your_account>.github.io/js_get_data_DOM/)

2022-07-19 12:51 UTC, Lentyaeev approved these changes
😉

2022-07-19 14:53 UTC, VETALEK requested changes
GJ 👍 
commented

2022-07-19 14:53 UTC, VETALEK commented on src/scripts/main.js
> +});
better use `reduce` here

2022-07-20 06:10 UTC, VETALEK approved these changes
🚀

2026-04-28 18:06 UTC, closed without merging