solution
mate-academy/js_get_data_DOM pull request #83
Opened 2020-10-12 11:53 UTC by andlap24

[DEMO LINK](https://andlap24.github.io/js_get_data_DOM/)

2020-10-12 13:01 UTC, taniaomelko requested changes
Додай toLocaleString(), щоб отримані дані були так само розділені комою по 3 знаки.

2020-10-12 13:03 UTC, andlap24 commented
> Додай toLocaleString(), щоб отримані дані були так само розділені комою по 3 знаки.

все вірно, дякую)

2020-10-12 13:31 UTC, taniaomelko approved these changes

2020-10-15 09:09 UTC, danheim requested changes

2020-10-15 09:09 UTC, danheim commented on src/scripts/main.js
> +const populationArr = [...population];
не дописывай arr никогда
сделай через одну переменную

2020-10-15 11:26 UTC, danheim approved these changes

2026-01-18 11:02 UTC, closed without merging