Task is done
mate-academy/js_get_data_DOM pull request #867
Opened 2023-03-22 00:58 UTC by NazikVr

[DEMO LINK](https://nazikvr.github.io/js_get_data_DOM/)

2023-03-22 08:57 UTC, tetiana-ivanchenko requested changes

2023-03-22 08:57 UTC, tetiana-ivanchenko commented on src/scripts/main.js
> +  return number.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',');
use .toLocaleString('en-US');

2023-03-22 08:57 UTC, tetiana-ivanchenko commented on src/scripts/main.js
> +}
use reduce and `.replace` method to remove commas and get sum

2025-08-18 08:02 UTC, etojeDenys approved these changes
good job

2025-10-08 16:19 UTC, closed without merging